FROM python:3.11-slim

RUN pip install --no-cache-dir \
    dagster==1.7.5 \
    dagster-webserver==1.7.5

# Install any additional pipeline dependencies if needed later
# RUN pip install pandas polars duckdb pyspark

WORKDIR /opt/dagster/app

ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p $DAGSTER_HOME
